# Generated by Django 5.1.3 on 2024-11-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniInfo',
            fields=[
                ('AlumniID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('MiddleName', models.CharField(blank=True, max_length=50, null=True)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('GradYear', models.IntegerField(blank=True, null=True)),
                ('DateOfBirth', models.DateField(blank=True, null=True)),
                ('CurrentCity', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
