# Generated by Django 5.1.3 on 2024-11-15 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AwardTitle', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('DateAwarded', models.DateField()),
                ('AlumniID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alumniinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('JobTitle', models.CharField(max_length=100)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('Skills', models.TextField()),
                ('AlumniID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alumniinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Platform', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50)),
                ('AlumniID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alumniinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree_Name', models.CharField(max_length=100)),
                ('CGPA', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('StartYear', models.IntegerField(blank=True, null=True)),
                ('EndYear', models.IntegerField(blank=True, null=True)),
                ('AlumniID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alumniinfo')),
            ],
            options={
                'unique_together': {('AlumniID', 'Degree_Name')},
            },
        ),
        migrations.CreateModel(
            name='AlumniPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryCode', models.CharField(max_length=5)),
                ('MobileNumber', models.CharField(max_length=10)),
                ('AlumniID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alumniinfo')),
            ],
            options={
                'unique_together': {('AlumniID', 'MobileNumber')},
            },
        ),
    ]
