# Generated by Django 5.1.3 on 2024-11-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_achievements_professionalhistory_socialmedia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academichistory',
            old_name='AlumniID',
            new_name='Alumni',
        ),
        migrations.RenameField(
            model_name='achievements',
            old_name='AlumniID',
            new_name='Alumni',
        ),
        migrations.RenameField(
            model_name='alumniphone',
            old_name='AlumniID',
            new_name='Alumni',
        ),
        migrations.RenameField(
            model_name='professionalhistory',
            old_name='AlumniID',
            new_name='Alumni',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='AlumniID',
            new_name='Alumni',
        ),
        migrations.AlterUniqueTogether(
            name='academichistory',
            unique_together={('Alumni', 'Degree_Name')},
        ),
        migrations.AlterUniqueTogether(
            name='alumniphone',
            unique_together={('Alumni', 'MobileNumber')},
        ),
    ]
